# Prahari — Indian Medications Database
# Curated list of top 30 most common Indian medications to provide local relevance (GSK India, Micro Labs, Cipla, Alkem, etc.)
# with local compositions, pricing, and clinically accurate, layman-friendly guidance.

INDIAN_DRUGS = {
    "dolo 650": {
        "brand_name": "Dolo 650",
        "generic_name": "Paracetamol",
        "manufacturer": "Micro Labs Ltd.",
        "product_type": "Analgesic & Antipyretic",
        "route": ["ORAL"],
        "rxcui": ["161"],
        "ndc": [],
        "indications": "Relief of mild to moderate pain (headache, toothache, muscle ache, backache, periods pain) and reduction of fever.",
        "dosage": "Adults: 1 tablet (650 mg) every 4 to 6 hours as needed. Do not exceed 4 tablets (2600 mg) in 24 hours unless directed by a doctor. Take with or after food to prevent mild stomach upset.",
        "warnings": "Severe liver damage may occur if you take more than the maximum daily dose, take it with other drugs containing paracetamol, or consume 3 or more alcoholic drinks daily while using this product.",
        "boxed_warning": "",
        "contraindications": "Hypersensitivity to paracetamol or severe active liver disease.",
        "adverse_reactions": "Nausea, vomiting, allergic skin rash, or itching. Rare but serious: skin peeling or severe allergic reactions (angioedema).",
        "drug_interactions": "Avoid taking with other paracetamol-containing products (like cold and flu tablets). Caution with blood thinners like Warfarin.",
        "precautions": "Consult a doctor if you have liver or kidney problems, or if you are pregnant or breastfeeding.",
        "storage": "Store below 30°C in a dry place. Keep out of reach of children.",
        "description": "Dolo 650 is India's most trusted fever reducer and pain reliever. Each tablet contains Paracetamol IP 650 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "calpol 500": {
        "brand_name": "Calpol 500",
        "generic_name": "Paracetamol",
        "manufacturer": "GlaxoSmithKline Pharmaceuticals India",
        "product_type": "Analgesic & Antipyretic",
        "route": ["ORAL"],
        "rxcui": ["161"],
        "ndc": [],
        "indications": "Treatment of mild to moderate pain and reducing fever (pyrexia). Commonly used for headaches, dental pain, body aches, and post-vaccination fever.",
        "dosage": "Adults: 1 to 2 tablets (500-1000 mg) every 4 to 6 hours as needed. Maximum 8 tablets (4000 mg) in 24 hours. Children (6-12 years): 1/2 to 1 tablet up to 4 times daily.",
        "warnings": "Avoid alcohol. Exceeding the daily limit of 4000 mg can lead to severe, irreversible liver failure.",
        "boxed_warning": "",
        "contraindications": "Do not take if you have severe hepatic impairment or are allergic to paracetamol.",
        "adverse_reactions": "Rare: skin rashes, blood disorders (neutropenia). Discontinue immediately if any allergic reaction occurs.",
        "drug_interactions": "Risk of increased bleeding with anticoagulants (e.g. Warfarin) if taken regularly.",
        "precautions": "Use with caution in patients with renal impairment, alcohol dependency, or chronic malnutrition.",
        "storage": "Protect from direct light and moisture. Store below 25°C.",
        "description": "Calpol is a household name in India for fever management. Each tablet contains Paracetamol IP 500 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "crocin pain relief": {
        "brand_name": "Crocin Pain Relief",
        "generic_name": "Paracetamol + Caffeine",
        "manufacturer": "GSK Consumer Healthcare India",
        "product_type": "Analgesic & Antipyretic",
        "route": ["ORAL"],
        "rxcui": ["161", "1886"],
        "ndc": [],
        "indications": "Fast relief from severe headaches, migraines, muscle pain, and joint pain.",
        "dosage": "Adults: 1 tablet every 4 to 6 hours. Do not exceed 6 tablets in 24 hours. Swallow whole with water, preferably after food.",
        "warnings": "Contains caffeine. Limit the use of caffeine-containing beverages (coffee, tea, colas) while taking this, as it may cause nervousness, irritability, or rapid heartbeat.",
        "boxed_warning": "",
        "contraindications": "Severe liver disease, high blood pressure (due to caffeine), or hypersensitivity to the components.",
        "adverse_reactions": "Insomnia, restlessness, stomach irritation, rapid pulse, and skin rashes.",
        "drug_interactions": "Do not combine with other painkillers or cold formulas containing paracetamol.",
        "precautions": "Not recommended for children under 12 years. Speak to a doctor if you are pregnant or have heart disease.",
        "storage": "Store in a cool, dry place. Keep blister strips in outer carton.",
        "description": "Crocin Pain Relief combines the pain-relieving action of Paracetamol (650 mg) with Caffeine (50 mg) which acts as an analgesic enhancer to speed up relief.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "combiflam": {
        "brand_name": "Combiflam",
        "generic_name": "Ibuprofen + Paracetamol",
        "manufacturer": "Sanofi India Ltd.",
        "product_type": "Non-Steroidal Anti-Inflammatory Drug (NSAID) Combination",
        "route": ["ORAL"],
        "rxcui": ["5614", "161"],
        "ndc": [],
        "indications": "Relief of inflammatory pain conditions (rheumatoid arthritis, osteoarthritis), dental pain, post-surgical pain, and fever accompanied by swelling or inflammation.",
        "dosage": "Adults: 1 tablet 3 times a day, strictly after meals to avoid stomach upset. Do not take on an empty stomach.",
        "warnings": "May cause severe stomach bleeding or ulcers. Avoid alcohol while taking this medicine as it increases the risk of stomach hemorrhage. Long-term use can affect kidney function.",
        "boxed_warning": "Warning: Combining Ibuprofen and Paracetamol increases the risk of gastrointestinal ulcers. Discontinue use if you experience black, tarry stools or vomit blood.",
        "contraindications": "History of stomach ulcers, asthma triggered by aspirin, severe heart failure, or active bleeding disorders.",
        "adverse_reactions": "Stomach pain, heartburn, indigestion, nausea, headache, dizziness, and fluid retention.",
        "drug_interactions": "Avoid taking with other blood thinners (Aspirin, Warfarin) or other NSAIDs (Diclofenac, Naproxen).",
        "precautions": "Use with extreme caution in elderly patients and those with a history of hypertension or kidney dysfunction.",
        "storage": "Store below 30°C. Protect from moisture and heat.",
        "description": "Combiflam is one of India's most popular combination tablets for pain and swelling. Each tablet contains Ibuprofen IP 400 mg and Paracetamol IP 325 mg.",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "zerodol-sp": {
        "brand_name": "Zerodol-SP",
        "generic_name": "Aceclofenac + Paracetamol + Serratiopeptidase",
        "manufacturer": "IPCA Laboratories Ltd.",
        "product_type": "Anti-inflammatory, Analgesic & Muscle/Tissue Healing Enzyme",
        "route": ["ORAL"],
        "rxcui": [],
        "ndc": [],
        "indications": "Reduction of severe pain, swelling, and inflammation associated with bone/joint injuries, arthritis, dental surgery, or muscle sprains.",
        "dosage": "Adults: 1 tablet twice daily (morning and night) after food. Do not take on an empty stomach.",
        "warnings": "Aceclofenac can cause severe gastrointestinal bleeding. Serratiopeptidase is a proteolytic enzyme that can interfere with blood clotting. Stop use if you experience easy bruising or bleeding.",
        "boxed_warning": "Warning: NSAID combination. Increases risk of stomach ulcers and bleeding. Do not use for prolonged periods without medical supervision.",
        "contraindications": "Active stomach ulcers, bleeding disorders, asthma, severe liver/kidney damage, or pregnancy.",
        "adverse_reactions": "Nausea, stomach pain, diarrhea, indigestion, loss of appetite, and skin rashes.",
        "drug_interactions": "Interacts with blood thinners, other NSAIDs, and blood pressure medications (ACE inhibitors).",
        "precautions": "Regular monitoring of kidney and liver function is advised for treatments lasting longer than 7 days.",
        "storage": "Store below 25°C in a dry place. Protect from light.",
        "description": "Zerodol-SP is a triple-action healing and pain relief formula. Each tablet contains Aceclofenac (100 mg), Paracetamol (325 mg), and Serratiopeptidase (15 mg).",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "omez": {
        "brand_name": "Omez",
        "generic_name": "Omeprazole",
        "manufacturer": "Dr. Reddy's Laboratories Ltd.",
        "product_type": "Proton Pump Inhibitor (PPI)",
        "route": ["ORAL"],
        "rxcui": ["7646"],
        "ndc": [],
        "indications": "Treatment of gastroesophageal reflux disease (GERD), acid acidity, heartburn, stomach ulcers, and Zollinger-Ellison syndrome.",
        "dosage": "Adults: 1 capsule (20 mg) daily in the morning, 30 to 60 minutes before breakfast on an empty stomach. Swallow whole with water; do not crush or chew.",
        "warnings": "Prolonged use (more than 1 year) may increase the risk of bone fractures (osteoporosis) and low magnesium levels. Long-term acid suppression can reduce Vitamin B12 absorption.",
        "boxed_warning": "",
        "contraindications": "Allergic to Omeprazole or other PPIs (Pantoprazole, Rabeprazole).",
        "adverse_reactions": "Headache, diarrhea, abdominal pain, flatulence (gas), nausea, and dizziness.",
        "drug_interactions": "Can decrease the absorption of drugs that require stomach acid (e.g. Ketoconazole, Iron supplements). Alters Clopidogrel (blood thinner) activity.",
        "precautions": "Report any unexpected weight loss, persistent diarrhea, or difficulty swallowing to your doctor.",
        "storage": "Store in a cool, dry place. Keep container tightly closed to protect from moisture.",
        "description": "Omez is India's leading antacid capsule. Each capsule contains Omeprazole IP 20 mg as enteric-coated granules.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "pan 40": {
        "brand_name": "Pan 40",
        "generic_name": "Pantoprazole",
        "manufacturer": "Alkem Laboratories Ltd.",
        "product_type": "Proton Pump Inhibitor (PPI)",
        "route": ["ORAL"],
        "rxcui": ["40356"],
        "ndc": [],
        "indications": "Heartburn, acid reflux, gastric and duodenal ulcers, and prevention of NSAID-induced stomach irritation.",
        "dosage": "Adults: 1 tablet (40 mg) daily in the morning, 30-60 minutes before breakfast. Swallow whole.",
        "warnings": "Take on an empty stomach. Do not take with food as it reduces the drug's efficacy. Extended use may lead to vitamin B12 deficiency.",
        "boxed_warning": "",
        "contraindications": "Known hypersensitivity to Pantoprazole.",
        "adverse_reactions": "Nausea, vomiting, flatulence, dry mouth, skin rash, sleep disturbances, and joint pain.",
        "drug_interactions": "Alters the absorption of antiretrovirals (Atazanavir) and antifungal azoles.",
        "precautions": "Inform your doctor if you have severe liver disease or history of osteoporosis.",
        "storage": "Store below 30°C. Protect from light and moisture.",
        "description": "Pan 40 is a highly prescribed gastro-resistant tablet in India. Each tablet contains Pantoprazole Sodium IP equivalent to Pantoprazole 40 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "pantocid": {
        "brand_name": "Pantocid",
        "generic_name": "Pantoprazole",
        "manufacturer": "Sun Pharmaceutical Industries Ltd.",
        "product_type": "Proton Pump Inhibitor (PPI)",
        "route": ["ORAL"],
        "rxcui": ["40356"],
        "ndc": [],
        "indications": "Acidity, heartburn, GERD, and healing of esophagus lesions caused by acid reflux.",
        "dosage": "Adults: 1 tablet daily on an empty stomach in the morning.",
        "warnings": "Always take 1 hour before eating. Prolonged use (over 3 months) can cause low blood magnesium levels (hypomagnesemia).",
        "boxed_warning": "",
        "contraindications": "Allergic to pantoprazole.",
        "adverse_reactions": "Diarrhea, headache, dizziness, flatulence, and muscle pain.",
        "drug_interactions": "Interacts with iron salts, ketoconazole, and methotrexate.",
        "precautions": "Consult a doctor if you are pregnant or breastfeeding.",
        "storage": "Store in dry place below 30°C.",
        "description": "Pantocid is a premium antacid tablet. Each tablet contains Pantoprazole 40 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "aciloc 150": {
        "brand_name": "Aciloc 150",
        "generic_name": "Ranitidine",
        "manufacturer": "Cadila Pharmaceuticals Ltd.",
        "product_type": "H2 Receptor Blocker (Antacid)",
        "route": ["ORAL"],
        "rxcui": ["9143"],
        "ndc": [],
        "indications": "Treatment of indigestion, heartburn, gas, acid reflux, stomach ulcers, and esophageal inflammation.",
        "dosage": "Adults: 1 tablet (150 mg) twice daily (morning and night), or 1 tablet (300 mg) at bedtime. Can be taken with or without food.",
        "warnings": "Limit alcohol intake, as this medication can increase blood alcohol concentrations. Do not take with other antacids within 1 hour.",
        "boxed_warning": "",
        "contraindications": "History of allergy to ranitidine or other H2 blockers (Famotidine, Cimetidine).",
        "adverse_reactions": "Headache, constipation, diarrhea, fatigue, muscle pain, and rare sleep disturbances.",
        "drug_interactions": "Can reduce absorption of ketoconazole, itraconazole, and iron supplements.",
        "precautions": "Consult doctor if you have kidney disease, as dosage adjustments may be needed.",
        "storage": "Store below 25°C in dry place. Protect from light.",
        "description": "Aciloc is a widely used and affordable antacid in India. Each tablet contains Ranitidine Hydrochloride IP equivalent to Ranitidine 150 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "montek-lc": {
        "brand_name": "Montek-LC",
        "generic_name": "Montelukast + Levocetirizine",
        "manufacturer": "Cipla Ltd.",
        "product_type": "Antihistamine & Leukotriene Receptor Antagonist",
        "route": ["ORAL"],
        "rxcui": ["38221", "260175"],
        "ndc": [],
        "indications": "Relief of symptoms of allergic rhinitis (sneezing, runny nose, itchy/watery eyes, nasal congestion) and chronic hives.",
        "dosage": "Adults: 1 tablet once daily, preferably at bedtime. Can be taken with or without food.",
        "warnings": "May cause moderate drowsiness. Avoid driving or operating heavy machinery after taking. Avoid alcohol as it increases sedation. Montelukast has been rarely linked to neuropsychiatric events (mood changes, anxiety).",
        "boxed_warning": "Warning: Montelukast component has been associated with neuropsychiatric changes. Watch for mood swings, agitation, depression, or suicidal thoughts.",
        "contraindications": "Severe kidney failure (creatinine clearance < 10 ml/min) or hypersensitivity to levocetirizine or montelukast.",
        "adverse_reactions": "Sleepiness, dry mouth, headache, fatigue, sore throat, and stomach pain.",
        "drug_interactions": "Caution when taken with Phenobarbital or Rifampin, which can reduce montelukast levels.",
        "precautions": "Not meant for the immediate relief of acute asthma attacks. Keep a rescue inhaler handy.",
        "storage": "Store below 30°C in a dry place. Protect from moisture.",
        "description": "Montek-LC is India's most prescribed allergy pill. Each tablet contains Montelukast Sodium IP (10 mg) and Levocetirizine Dihydrochloride IP (5 mg).",
        "has_boxed_warning": True,
        "urgency_level": "moderate"
    },
    "cetcip": {
        "brand_name": "Cetcip",
        "generic_name": "Cetirizine",
        "manufacturer": "Cipla Ltd.",
        "product_type": "Antihistamine (Anti-allergic)",
        "route": ["ORAL"],
        "rxcui": ["20610"],
        "ndc": [],
        "indications": "Allergic symptoms like runny nose, sneezing, hives, watery eyes, and skin itching.",
        "dosage": "Adults: 1 tablet (10 mg) once daily, preferably in the evening. Can be taken with or without food.",
        "warnings": "Avoid alcohol as it increases drowsiness. Do not drive or perform hazardous tasks if you feel sedated.",
        "contraindications": "Allergic to cetirizine or hydroxyzine. Severe renal impairment.",
        "adverse_reactions": "Drowsiness, fatigue, dry mouth, headache, and sore throat.",
        "drug_interactions": "Avoid taking with other sedative medicines or sleeping pills.",
        "precautions": "Consult doctor if you are pregnant or breastfeeding.",
        "storage": "Store below 30°C in a dry place.",
        "description": "Cetcip is a popular, cost-effective anti-allergy tablet. Each tablet contains Cetirizine Dihydrochloride 10 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "azithral 500": {
        "brand_name": "Azithral 500",
        "generic_name": "Azithromycin",
        "manufacturer": "Alembic Pharmaceuticals Ltd.",
        "product_type": "Macrolide Antibiotic",
        "route": ["ORAL"],
        "rxcui": ["18631"],
        "ndc": [],
        "indications": "Treatment of bacterial infections (throat infections, tonsillitis, bronchitis, pneumonia, skin infections, typhoid, and certain sexually transmitted diseases).",
        "dosage": "Adults: 1 tablet (500 mg) once daily for 3 to 5 days. Take 1 hour before or 2 hours after food for optimal absorption.",
        "warnings": "Complete the full prescribed course even if symptoms disappear. Do not stop early to prevent bacterial resistance. Seek immediate help if you develop severe watery diarrhea or stomach cramps.",
        "boxed_warning": "Warning: Can cause an abnormal heart rhythm (QT prolongation). Seek immediate care if you experience chest pain, rapid/fluttering heartbeat, or sudden fainting.",
        "contraindications": "History of cholestatic jaundice or liver problems associated with prior use of azithromycin.",
        "adverse_reactions": "Diarrhea, nausea, abdominal pain, vomiting, flatulence, and temporary hearing changes (rare).",
        "drug_interactions": "Do not take with antacids containing aluminum or magnesium (take 2 hours apart). Care with Digoxin.",
        "precautions": "Caution in patients with heart arrhythmias, low blood potassium levels, or myasthenia gravis.",
        "storage": "Store below 25°C in a dry place.",
        "description": "Azithral 500 is a powerful, short-course antibiotic in India. Each tablet contains Azithromycin Dihydrate IP equivalent to anhydrous Azithromycin 500 mg.",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "augmentin 625 duo": {
        "brand_name": "Augmentin 625 Duo",
        "generic_name": "Amoxicillin + Clavulanic Acid",
        "manufacturer": "GlaxoSmithKline Pharmaceuticals India",
        "product_type": "Penicillin Antibiotic + Beta-Lactamase Inhibitor",
        "route": ["ORAL"],
        "rxcui": ["317208"],
        "ndc": [],
        "indications": "Middle ear infections, sinus infections, throat/respiratory tract infections, urinary tract infections, skin/soft tissue infections.",
        "dosage": "Adults: 1 tablet twice daily (every 12 hours) with a meal to reduce stomach discomfort and enhance absorption.",
        "warnings": "Finish the entire course. Can cause severe antibiotic-associated diarrhea (C. diff). Allergic reactions can be severe and life-threatening (anaphylaxis).",
        "boxed_warning": "Warning: Severe allergic reactions (anaphylaxis). If you experience difficulty breathing, swelling of the face, or a severe skin rash with peeling, stop use and seek emergency care.",
        "contraindications": "History of penicillin allergy, or history of liver dysfunction/jaundice associated with Amoxicillin/Clavulanate.",
        "adverse_reactions": "Diarrhea, nausea, vomiting, oral thrush (fungal infection), and skin rash.",
        "drug_interactions": "Can decrease the effectiveness of oral contraceptive pills. Interacts with Allopurinol (gout medicine).",
        "precautions": "Inform your doctor if you have kidney or liver disease.",
        "storage": "Store in cool, dry place. Keep out of reach of children.",
        "description": "Augmentin is the gold-standard broad-spectrum antibiotic. Each tablet contains Amoxicillin Trihydrate (500 mg) and Potassium Clavulanate (125 mg).",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "glycomet 500": {
        "brand_name": "Glycomet 500",
        "generic_name": "Metformin",
        "manufacturer": "USV Private Ltd.",
        "product_type": "Biguanide Antidiabetic",
        "route": ["ORAL"],
        "rxcui": ["6809"],
        "ndc": [],
        "indications": "Treatment of Type 2 Diabetes Mellitus, especially in overweight patients, to control blood sugar levels. Also used off-label for PCOS.",
        "dosage": "Adults: 1 tablet once or twice daily with or immediately after meals to reduce stomach side effects. Swallow whole.",
        "warnings": "Rare but serious risk of Lactic Acidosis (acid build-up in blood), especially in patients with severe kidney or liver disease. Avoid excessive alcohol as it increases this risk.",
        "boxed_warning": "Warning: Lactic Acidosis. Symptoms include deep rapid breathing, severe muscle pain, cold skin, extreme fatigue, or slow heartbeat. Seek emergency care immediately.",
        "contraindications": "Severe kidney failure (eGFR < 30 ml/min), acute dehydration, diabetic ketoacidosis, or recent heart attack.",
        "adverse_reactions": "Nausea, vomiting, diarrhea, metallic taste, abdominal pain, loss of appetite, and Vitamin B12 deficiency (long-term).",
        "drug_interactions": "Contrast dyes (injectable tests) can increase kidney strain — stop Glycomet 48 hours before tests.",
        "precautions": "Get regular kidney function tests (creatinine) and blood sugar monitoring.",
        "storage": "Store below 30°C. Protect from moisture.",
        "description": "Glycomet is India's most popular metformin brand for diabetes control. Each tablet contains Metformin Hydrochloride IP 500 mg.",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "telma 40": {
        "brand_name": "Telma 40",
        "generic_name": "Telmisartan",
        "manufacturer": "Glenmark Pharmaceuticals Ltd.",
        "product_type": "Angiotensin II Receptor Blocker (ARB)",
        "route": ["ORAL"],
        "rxcui": ["37302"],
        "ndc": [],
        "indications": "Treatment of hypertension (high blood pressure) to reduce the risk of stroke, heart attack, and kidney complications.",
        "dosage": "Adults: 1 tablet (40 mg) once daily, at the same time each day, with or without food. Ensure regular blood pressure checks.",
        "warnings": "Avoid high-potassium foods (bananas, potatoes, spinach) and potassium-based salt substitutes, as Telmisartan can cause hyperkalemia (high blood potassium).",
        "boxed_warning": "Warning: Fetal Toxicity. Do not take during pregnancy. Telmisartan can cause severe injury or death to the developing fetus.",
        "contraindications": "Pregnancy, breastfeeding, or severe biliary obstruction.",
        "adverse_reactions": "Dizziness, low blood pressure (hypotension), back pain, sinus congestion, and elevated potassium levels.",
        "drug_interactions": "Increased risk of kidney damage when taken with NSAIDs (Combiflam, Zerodol). Can increase Lithium levels.",
        "precautions": "Perform regular kidney function and potassium level blood tests.",
        "storage": "Store in original blister pack to protect from moisture. Do not remove until ready to take.",
        "description": "Telma 40 is a leading blood pressure medication. Each tablet contains Telmisartan IP 40 mg.",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "asthalin inhaler": {
        "brand_name": "Asthalin Inhaler",
        "generic_name": "Salbutamol",
        "manufacturer": "Cipla Ltd.",
        "product_type": "Beta-2 Adrenergic Agonist (Bronchodilator)",
        "route": ["RESPIRATORY (INHALATION)"],
        "rxcui": ["9524"],
        "ndc": [],
        "indications": "Relief and prevention of bronchospasm in patients with asthma, chronic obstructive pulmonary disease (COPD), and exercise-induced bronchospasm.",
        "dosage": "Adults and Children: 1 to 2 puffs (100-200 mcg) as needed for immediate relief of wheezing or shortness of breath. Maximum 8 puffs in 24 hours.",
        "warnings": "Avoid excessive caffeine (coffee, tea, cola, chocolate) as it can compound Salbutamol's stimulating effects, causing high heart rate, severe anxiety, or tremors.",
        "boxed_warning": "",
        "contraindications": "Hypersensitivity to Salbutamol or other inhaler components.",
        "adverse_reactions": "Tremors (shaky hands), headache, rapid heartbeat (tachycardia), palpitations, throat irritation, and muscle cramps.",
        "drug_interactions": "Beta-blockers (like Atenolol) can block Salbutamol's effects and trigger severe asthma attacks.",
        "precautions": "If you need to use this rescue inhaler more than 2-3 times a week, it indicates poor asthma control; consult your doctor.",
        "storage": "Store below 30°C. Do not freeze. Keep away from direct sunlight.",
        "description": "Asthalin is India's most trusted rescue inhaler for quick breathing relief. Each puff delivers Salbutamol Sulfate IP equivalent to Salbutamol 100 mcg.",
        "has_boxed_warning": False,
        "urgency_level": "moderate"
    },
    "becosules capsules": {
        "brand_name": "Becosules",
        "generic_name": "Vitamin B-Complex + Vitamin C",
        "manufacturer": "Pfizer India Ltd.",
        "product_type": "Nutritional Supplement",
        "route": ["ORAL"],
        "rxcui": [],
        "ndc": [],
        "indications": "Treatment of vitamin deficiencies, mouth ulcers, hair fall, fatigue, and recovery after antibiotic therapy or illness.",
        "dosage": "Adults: 1 capsule daily after a meal. Swallow whole with water.",
        "warnings": "Your urine will turn a bright yellow color while taking this medicine. This is completely harmless and is simply the body excreting excess Vitamin B2 (Riboflavin).",
        "boxed_warning": "",
        "contraindications": "None when taken at recommended dose.",
        "adverse_reactions": "Mild stomach upset, nausea, or headache. Very rare: allergic skin reactions.",
        "drug_interactions": "Vitamin B6 can reduce the effectiveness of levodopa (Parkinson's drug) unless taken with carbidopa.",
        "precautions": "Not intended to diagnose or treat chronic medical conditions.",
        "storage": "Store in a cool, dry place below 25°C. Keep bottle tightly closed.",
        "description": "Becosules is India's household vitamin B complex capsule, enriched with Vitamin C to support immunity and healing.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "limcee 500": {
        "brand_name": "Limcee 500",
        "generic_name": "Vitamin C (Ascorbic Acid)",
        "manufacturer": "Abbott India Ltd.",
        "product_type": "Nutritional Supplement",
        "route": ["ORAL"],
        "rxcui": ["11563"],
        "ndc": [],
        "indications": "Prevention and treatment of Vitamin C deficiency (scurvy), boosting immunity, wound healing, and skin health.",
        "dosage": "Adults: Chew 1 tablet (500 mg) daily. This is a chewable tablet; do not swallow it whole.",
        "warnings": "Excessive intake of Vitamin C (more than 2000 mg/day) can cause stomach cramps, diarrhea, and raise risk of kidney stones.",
        "boxed_warning": "",
        "contraindications": "Known kidney stones or hyperoxaluria.",
        "adverse_reactions": "Diarrhea, nausea, stomach cramps, and frequent urination at high doses.",
        "drug_interactions": "Can increase absorption of iron supplements. May reduce effect of blood thinners (Warfarin) at high doses.",
        "precautions": "Consult doctor if you have history of kidney stones.",
        "storage": "Keep strip in dry, dark place below 25°C.",
        "description": "Limcee is an orange-flavored chewable Vitamin C tablet widely used in India. Each tablet contains Ascorbic Acid IP 100 mg and Sodium Ascorbate IP 450 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "shelcal 500": {
        "brand_name": "Shelcal 500",
        "generic_name": "Calcium + Vitamin D3",
        "manufacturer": "Torrent Pharmaceuticals Ltd.",
        "product_type": "Calcium and Vitamin D3 Supplement",
        "route": ["ORAL"],
        "rxcui": ["315264"],
        "ndc": [],
        "indications": "Management of osteoporosis, calcium deficiency, pregnancy/lactation calcium support, and weak bones.",
        "dosage": "Adults: 1 tablet daily after food (preferably dinner, as calcium is absorbed best at night).",
        "warnings": "Do not take within 2 hours of eating iron-rich foods, spinach, or taking thyroid medications (thyroxine), as calcium binds to them and prevents their absorption.",
        "boxed_warning": "",
        "contraindications": "Hypercalcemia (high blood calcium levels), severe kidney stones, or vitamin D toxicity.",
        "adverse_reactions": "Constipation, flatulence, bloating, and nausea.",
        "drug_interactions": "Reduces absorption of antibiotics (Fluoroquinolones, Tetracyclines) and Levothyroxine. Take 4 hours apart.",
        "precautions": "Ensure adequate hydration. Check blood calcium levels periodically during long-term use.",
        "storage": "Store in dry place below 30°C.",
        "description": "Shelcal 500 is India's most recommended calcium supplement. Each tablet contains Calcium Carbonate from oyster shell equivalent to elemental Calcium 500 mg and Vitamin D3 (Cholecalciferol) 250 IU.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "digene tablet": {
        "brand_name": "Digene",
        "generic_name": "Antacid (Magnesium + Aluminium Hydroxide + Simethicone)",
        "manufacturer": "Abbott India Ltd.",
        "product_type": "Antacid & Anti-flatulence",
        "route": ["ORAL"],
        "rxcui": [],
        "ndc": [],
        "indications": "Fast relief from acidity, heartburn, gas, flatulence, and bloated stomach feelings.",
        "dosage": "Adults: Chew 2 to 4 tablets after meals or when experiencing acidity. Do not swallow whole.",
        "warnings": "Do not take this antacid at the same time as other medications. Antacids coat the stomach and block the absorption of almost all prescription medicines (take other drugs 2 hours before or 4 hours after).",
        "boxed_warning": "",
        "contraindications": "Severe kidney failure (magnesium accumulation risk) or suspected appendicitis.",
        "adverse_reactions": "Constipation (from aluminium) or mild diarrhea (from magnesium).",
        "drug_interactions": "Blocks absorption of Iron, Calcium, Thyroxine, Ciprofloxacin, and Doxycycline.",
        "precautions": "Do not use continuously for more than 2 weeks without consulting a doctor.",
        "storage": "Store in a cool, dry place. Keep strips away from moisture.",
        "description": "Digene is a chewable, sugar-free pink tablet known for quick acidity relief. Contains Aluminium Hydroxide (300 mg), Magnesium Hydroxide (25 mg), Sodium Carboxymethylcellulose (100 mg), and Simethicone (25 mg).",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "saridon": {
        "brand_name": "Saridon",
        "generic_name": "Paracetamol + Propyphenazone + Caffeine",
        "manufacturer": "Piramal Enterprises Ltd.",
        "product_type": "Analgesic Combination",
        "route": ["ORAL"],
        "rxcui": [],
        "ndc": [],
        "indications": "Relief of severe headache, toothache, monthly period cramps, and joint pains.",
        "dosage": "Adults: 1 tablet as needed. Do not exceed 3 tablets in 24 hours. Take after food.",
        "warnings": "Do not take with other paracetamol medicines. Propyphenazone can cause allergic skin reactions. Limit caffeine drinks.",
        "boxed_warning": "",
        "contraindications": "Severe active liver or kidney disease, or allergy to pyrazolones.",
        "adverse_reactions": "Rashes, itching, rapid heartbeat, and mild gastrointestinal discomfort.",
        "drug_interactions": "Avoid blood thinners and other pain relief medicines.",
        "precautions": "Not for children under 12. Use only short-term.",
        "storage": "Store below 25°C in dry place.",
        "description": "Saridon is a quick-acting headache relief tablet in India. Contains Paracetamol (250 mg), Propyphenazone (150 mg), and Caffeine (50 mg).",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "liv.52": {
        "brand_name": "Liv.52",
        "generic_name": "Herbal Liver Protection Formulation",
        "manufacturer": "Himalaya Wellness Company",
        "product_type": "Herbal Hepatoprotective Supplement",
        "route": ["ORAL"],
        "rxcui": [],
        "ndc": [],
        "indications": "Prevention and treatment of infective hepatitis, alcohol-induced liver damage, early-stage cirrhosis, and loss of appetite.",
        "dosage": "Adults: 2 to 3 tablets twice or thrice daily before meals. Children: 1 to 2 tablets twice daily.",
        "warnings": "This is a phytopharmaceutical (herbal) formulation. While generally very safe, consult a doctor if you have severe obstructive jaundice or advanced liver failure.",
        "boxed_warning": "",
        "contraindications": "Hypersensitivity to any of the herbal ingredients.",
        "adverse_reactions": "Extremely rare; mild laxative effect or digestive comfort when started.",
        "drug_interactions": "May reduce the absorption of certain medications if taken simultaneously; space them by 1 hour.",
        "precautions": "Not a substitute for medical treatments for chronic hepatitis B or C.",
        "storage": "Store in cool, dry place away from direct sunlight. Do not refrigerate.",
        "description": "Liv.52 is India's most famous liver health supplement, containing extracts of Himsra (Capparis spinosa) and Kasani (Cichorium intybus).",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "dulcolax": {
        "brand_name": "Dulcolax",
        "generic_name": "Bisacodyl",
        "manufacturer": "Sanofi India Ltd.",
        "product_type": "Stimulant Laxative",
        "route": ["ORAL"],
        "rxcui": ["1701"],
        "ndc": [],
        "indications": "Short-term relief of occasional constipation, and bowel clearance before diagnostic medical tests.",
        "dosage": "Adults: 1 to 2 tablets (5-10 mg) at bedtime. Swallow whole; do not chew or crush. Works in 6 to 12 hours.",
        "warnings": "Do not take this tablet within 1 hour of drinking milk or taking an antacid, as it will dissolve the enteric coating too early, causing severe abdominal cramps and vomiting.",
        "boxed_warning": "",
        "contraindications": "Intestinal obstruction, appendicitis, acute inflammatory bowel disease, or severe dehydration.",
        "adverse_reactions": "Abdominal cramps, watery diarrhea, nausea, muscle weakness, and potassium loss (long-term).",
        "drug_interactions": "Diuretics and corticosteroids can increase potassium loss if combined with laxatives.",
        "precautions": "Do not use daily for more than 7 days, as it can create bowel dependency on laxatives.",
        "storage": "Store below 30°C in a dry place.",
        "description": "Dulcolax is India's standard overnight constipation relief pill. Each enteric-coated tablet contains Bisacodyl IP 5 mg.",
        "has_boxed_warning": False,
        "urgency_level": "safe"
    },
    "lasix": {
        "brand_name": "Lasix",
        "generic_name": "Furosemide",
        "manufacturer": "Sanofi India Ltd.",
        "product_type": "Loop Diuretic (Water Pill)",
        "route": ["ORAL"],
        "rxcui": ["4603"],
        "ndc": [],
        "indications": "Treatment of edema (fluid retention) associated with heart failure, liver cirrhosis, or kidney disease, and management of high blood pressure.",
        "dosage": "Adults: 1 tablet (40 mg) once daily in the morning. Taking it in the morning prevents waking up at night to urinate.",
        "warnings": "Lasix causes rapid loss of water and potassium. Avoid black licorice. Ensure consistent dietary intake of potassium-rich foods (bananas, oranges). Monitor for muscle cramps or weakness.",
        "boxed_warning": "Warning: Potent Diuretic. Can lead to profound diuresis with water and electrolyte depletion. Careful medical supervision is required.",
        "contraindications": "Complete inability to urinate (anuria) or severe electrolyte depletion.",
        "adverse_reactions": "Frequent urination, low blood pressure, muscle cramps, dehydration, dizziness, and low sodium/potassium.",
        "drug_interactions": "Increases toxicity of Lithium and Aminoglycoside antibiotics. NSAIDs can reduce its diuretic effect.",
        "precautions": "Regular blood tests for potassium, sodium, and kidney function are required.",
        "storage": "Store below 30°C. Protect from light.",
        "description": "Lasix is the standard loop diuretic. Each tablet contains Furosemide IP 40 mg.",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    },
    "voveran sr 100": {
        "brand_name": "Voveran SR 100",
        "generic_name": "Diclofenac Sodium",
        "manufacturer": "Novartis India Ltd.",
        "product_type": "NSAID (Painkiller)",
        "route": ["ORAL"],
        "rxcui": ["3355"],
        "ndc": [],
        "indications": "Relief of pain and inflammation in osteoarthritis, rheumatoid arthritis, gout, and severe muscle skeletal injury.",
        "dosage": "Adults: 1 tablet (100 mg SR) daily after meals. Swallow whole; do not break or chew, as it is a sustained-release formula.",
        "warnings": "Strictly take after food. Diclofenac can cause stomach lining erosion and severe gastrointestinal bleeding. Avoid alcohol.",
        "boxed_warning": "Warning: Cardiovascular & Gastrointestinal Risk. NSAIDs increase risk of stomach bleeding and serious cardiovascular thrombotic events (heart attack/stroke).",
        "contraindications": "Active stomach ulcers, recent bypass surgery (CABG), severe kidney failure, or aspirin-induced asthma.",
        "adverse_reactions": "Acid reflux, stomach pain, nausea, headache, dizziness, rashes, and elevated liver enzymes.",
        "drug_interactions": "Increases risk of bleeding with Aspirin, Clopidogrel, or Warfarin.",
        "precautions": "Use lowest effective dose for the shortest duration necessary.",
        "storage": "Store below 30°C. Protect from moisture.",
        "description": "Voveran SR 100 is India's leading sustained-release Diclofenac. Each tablet contains Diclofenac Sodium IP 100 mg.",
        "has_boxed_warning": True,
        "urgency_level": "critical"
    }
}
