// deps: none
// Bilingual English/Hindi Translation dictionary and helper functions for Prahari

export const TRANSLATIONS = {
  en: {
    // General
    app_title: "Prahari",
    app_subtitle: "Health Sentinel",
    guardian_text: "Guardian of Your Health",
    privacy_title: "Privacy First",
    privacy_desc: "All health data stays on this device. No information leaves your browser.",
    loading: "Loading...",
    error: "Error",
    retry: "Retry",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    confirm_and_save: "Confirm & Save",
    edit: "Edit",
    delete: "Delete",
    back: "Back",
    next: "Next",
    submit: "Submit",
    warning: "Warning",
    critical: "Critical",
    success: "Success",
    offline_msg: "Viewing cached offline data.",

    // Feature 1: Pill Scan
    pill_scan_title: "Pill Visual Scan",
    pill_scan_subtitle: "Isolate and identify pills on-device using camera and AI",
    camera_viewfinder: "Align pill in center reticle",
    tap_to_scan: "Tap to Scan Now",
    scanning_active: "Analyzing camera frame...",
    contour_error_title: "Pill not clearly detected",
    contour_error_msg: "Place pill flat on a white surface, ensure good lighting and no background clutter.",
    onnx_loading: "Initializing ONNX Classifier...",
    match_confidence: "Match Confidence",
    dosage_info: "Dosage Info",
    warnings_info: "Warnings / Interactions",
    missed_dose_guide: "Missed Dose Guidance",
    add_to_cabinet: "Add to My Cabinet",
    scan_another: "Scan Another",
    pill_shape_round: "Round",
    pill_shape_oval: "Oval",
    pill_shape_unknown: "Unknown",
    camera_denied: "Camera access was denied. Please check site permissions.",
    opencv_timeout: "OpenCV processing timed out. Please try again.",
    onnx_failed: "ONNX classifier was unable to load.",

    // Feature 2: Chronotherapy
    scheduler_title: "Daily Scheduler",
    scheduler_subtitle: "AI Chronotherapy Schedule Optimizer",
    med_list: "Medication List",
    add_med_placeholder: "Search & add a medication...",
    pref_title: "Daily Routine Times",
    wake_time: "Wake Time",
    sleep_time: "Sleep Time",
    breakfast_time: "Breakfast",
    lunch_time: "Lunch",
    dinner_time: "Dinner",
    btn_optimize: "Optimize My Schedule",
    optimizing_step_1: "Checking drug-drug interactions...",
    optimizing_step_2: "Solving constraint equations...",
    optimizing_step_3: "Applying chronotherapy rules...",
    optimizing_step_4: "Finalizing schedule slots...",
    optimal_timing: "Optimal Chrono-Timing",
    dose_chips: "Scheduled Doses",
    no_solution: "Constraint solver found no conflict-free arrangement. Relaxing soft guidelines.",
    total_doses: "Total Doses",
    unresolved_conflicts: "Unresolved Conflicts",
    resolved_conflicts: "Conflicts Resolved Successfully",
    export_ics: "Export to Calendar (.ics)",
    export_pdf: "Print/Export as PDF",
    timeline_view: "24-Hour Timeline Flow",
    empty_scheduler: "Add medicines in your cabinet or list to optimize daily timing.",
    conflict_detected: "Interaction Conflict Alert!",

    // Feature 3: Paper to Dashboard
    paper_locker_title: "Report Locker",
    paper_locker_subtitle: "Lab Report Scanner & Biomarker Trends",
    tab_upload: "Upload & Scan",
    tab_locker: "My Report Locker",
    tab_trends: "Trend Dashboard",
    drag_drop_zone: "Drag and drop report image/PDF, or click to browse",
    supported_formats: "Supports PNG, JPG, or PDF scans",
    deskewing: "Deskewing and binarizing image...",
    grid_isolating: "Isolating report table cells...",
    ocr_running: "Running Tesseract.js multilingual OCR...",
    parsing_structured: "Parsing report text parameters...",
    save_complete: "Report saved successfully!",
    report_date: "Report Date",
    lab_name: "Laboratory Name",
    patient_name: "Patient Name",
    verify_extracted: "Verify Extracted Data",
    extracted_test: "Biomarker Parameter",
    extracted_val: "Result Value",
    extracted_unit: "Unit",
    extracted_range: "Reference Range",
    extracted_status: "Status",
    status_normal: "Normal",
    status_high: "High",
    status_low: "Low",
    status_critical: "Critical",
    locker_empty: "No lab reports stored yet. Scan your first report to build trend charts.",
    delete_report_confirm: "Are you sure you want to delete this lab report?",
    biomarker_category: "Category",
    biomarker_trends: "Biomarker Trendlines",
    trend_select_test: "Select biomarker to view chart",
    reference_band: "Healthy Reference Interval"
  },
  hi: {
    // General
    app_title: "प्रहरी",
    app_subtitle: "स्वास्थ्य रक्षक",
    guardian_text: "आपकी सेहत का पहरेदार",
    privacy_title: "गोपनीयता सर्वोपरि",
    privacy_desc: "सभी स्वास्थ्य डेटा इसी डिवाइस पर रहता है। आपका कोई भी डेटा इंटरनेट पर नहीं जाता।",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    retry: "पुनः प्रयास करें",
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    confirm_and_save: "पुष्टि करें और सहेजें",
    edit: "संपादित करें",
    delete: "हटाएं",
    back: "पीछे",
    next: "आगे",
    submit: "जमा करें",
    warning: "चेतावनी",
    critical: "गंभीर चेतावनी",
    success: "सफलता",
    offline_msg: "कैश किया गया ऑफ़लाइन डेटा देख रहे हैं।",

    // Feature 1: Pill Scan
    pill_scan_title: "दवा विज़ुअल स्कैन",
    pill_scan_subtitle: "कैमरा और एआई की मदद से अपने फोन पर दवा की पहचान करें",
    camera_viewfinder: "दवा को बीच वाले घेरे में रखें",
    tap_to_scan: "स्कैन करने के लिए दबाएं",
    scanning_active: "कैमरा फ्रेम का विश्लेषण किया जा रहा है...",
    contour_error_title: "दवा स्पष्ट रूप से नहीं दिखी",
    contour_error_msg: "दवा को सफेद सतह पर सपाट रखें, अच्छा प्रकाश सुनिश्चित करें और आसपास साफ रखें।",
    onnx_loading: "एआई मॉडल लोड हो रहा है...",
    match_confidence: "सटीकता दर",
    dosage_info: "खुराक की जानकारी",
    warnings_info: "चेतावनी / परस्पर प्रभाव",
    missed_dose_guide: "खुराक छूटने पर निर्देश",
    add_to_cabinet: "मेरी कैबिनेट में जोड़ें",
    scan_another: "दूसरा स्कैन करें",
    pill_shape_round: "गोल",
    pill_shape_oval: "अंडाकार",
    pill_shape_unknown: "अज्ञात",
    camera_denied: "कैमरा अनुमति अस्वीकृत कर दी गई थी। कृपया अनुमति जांचें।",
    opencv_timeout: "छवि विश्लेषण का समय समाप्त हो गया। कृपया पुन: प्रयास करें।",
    onnx_failed: "एआई वर्गीकरण मॉडल लोड नहीं हो सका।",

    // Feature 2: Chronotherapy
    scheduler_title: "दवा समय सारणी",
    scheduler_subtitle: "एआई क्रोनोथेरेपी अनुकूलक",
    med_list: "दवाइयों की सूची",
    add_med_placeholder: "दवा खोजें और जोड़ें...",
    pref_title: "दैनिक दिनचर्या का समय",
    wake_time: "जागने का समय",
    sleep_time: "सोने का समय",
    breakfast_time: "नाश्ता",
    lunch_time: "दोपहर का भोजन",
    dinner_time: "रात का भोजन",
    btn_optimize: "समय सारणी अनुकूलित करें",
    optimizing_step_1: "दवाओं के आपसी दुष्प्रभाव की जांच की जा रही है...",
    optimizing_step_2: "समय बाधाओं को हल किया जा रहा है...",
    optimizing_step_3: "क्रोनोथेरेपी नियमों को लागू किया जा रहा है...",
    optimizing_step_4: "अंतिम समय स्लॉट तय किए जा रहे हैं...",
    optimal_timing: "सर्वोत्तम क्रोनो-टाइमिंग",
    dose_chips: "निर्धारित खुराक",
    no_solution: "दवाओं के टकराव के बिना कोई समय तय नहीं हो सका। सामान्य नियमों में ढील दी जा रही है।",
    total_doses: "कुल खुराक",
    unresolved_conflicts: "अनसुलझे आपसी टकराव",
    resolved_conflicts: "दवा टकराव सफलतापूर्वक सुलझाया गया",
    export_ics: "कैलेंडर में जोड़ें (.ics)",
    export_pdf: "प्रिंट या पीडीएफ डाउनलोड करें",
    timeline_view: "२४-घंटे की समय सारणी",
    empty_scheduler: "दैनिक समय को सही करने के लिए कैबिनेट में दवाएं जोड़ें।",
    conflict_detected: "दवा आपसी प्रभाव चेतावनी!",

    // Feature 3: Paper to Dashboard
    paper_locker_title: "रिपोर्ट लॉकर",
    paper_locker_subtitle: "लैब रिपोर्ट स्कैनर और रुझान",
    tab_upload: "अपलोड और स्कैन",
    tab_locker: "मेरा रिपोर्ट लॉकर",
    tab_trends: "स्वास्थ्य रुझान चार्ट",
    drag_drop_zone: "रिपोर्ट छवि/पीडीएफ को यहां खींचें या ब्राउज़ करें",
    supported_formats: "PNG, JPG, या PDF का समर्थन करता है",
    deskewing: "दस्तावेज़ को सीधा और स्पष्ट किया जा रहा है...",
    grid_isolating: "रिपोर्ट तालिका खानों को अलग किया जा रहा है...",
    ocr_running: "टैसेरैक्ट ओसीआर पाठ निकाला जा रहा है...",
    parsing_structured: "रिपोर्ट पैरामीटर का विश्लेषण किया जा रहा है...",
    save_complete: "रिपोर्ट सफलतापूर्वक सहेजी गई!",
    report_date: "रिपोर्ट की तिथि",
    lab_name: "प्रयोगशाला का नाम",
    patient_name: "मरीज का नाम",
    verify_extracted: "निकाले गए डेटा को सत्यापित करें",
    extracted_test: "परीक्षण पैरामीटर",
    extracted_val: "परीक्षण परिणाम",
    extracted_unit: "इकाई",
    extracted_range: "सामान्य सीमा",
    extracted_status: "स्थिति",
    status_normal: "सामान्य",
    status_high: "उच्च",
    status_low: "कम",
    status_critical: "गंभीर",
    locker_empty: "अभी तक कोई लैब रिपोर्ट सहेजी नहीं गई है। रुझान चार्ट देखने के लिए पहली रिपोर्ट स्कैन करें।",
    delete_report_confirm: "क्या आप वाकई इस रिपोर्ट को हटाना चाहते हैं?",
    biomarker_category: "श्रेणी",
    biomarker_trends: "स्वास्थ्य रुझान रेखाएं",
    trend_select_test: "रुझान चार्ट देखने के लिए पैरामीटर चुनें",
    reference_band: "स्वस्थ सामान्य सीमा"
  }
};

/**
 * Retrieve translation label for given language, key and optional fallbacks.
 * @param {string} lang - 'en' or 'hi'
 * @param {string} key - Dictionary key
 * @returns {string} Translated string
 */
export function t(lang, key) {
  const targetLang = lang === 'hi' ? 'hi' : 'en';
  return TRANSLATIONS[targetLang][key] || TRANSLATIONS['en'][key] || key;
}
